NPM_TOKEN|TOKEN(\'|\"|\ |=)|:x-oauth-basic|([A-Za-z0-9_]{10,}\:[A-Za-z0-9_-]{10,})	0	lud1161_personal	Low	Certain
([^A-Z0-9]|^)(AKIA|A3T|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{12,}	0	gf_aws_keys	Low	Certain
([^A-Za-z0-9+/]|^)(eyJ|YTo|Tzo|PD[89]|aHR0cHM6L|aHR0cDo|rO0)[%a-zA-Z0-9+/]+={0,2}	0	gf_base_64	Low	Certain
AIza[0-9A-Za-z-_]{35}	0	gf_google_api	High	Certain
ya29\.[0-9A-Za-z\-_]+	0	gf_google_oauth	High	Certain
AKIA[0-9A-Z]{16}	0	gf_amazon_aws_access_key_id	High	Certain
amzn\\.mws\\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}	0	gf_amazon_aws_auth_token	High	Certain
s3\.amazonaws.com[/]+|[a-zA-Z0-9_-]*\.s3\.amazonaws.com	0	gf_amazon_aws_url	High	Certain
EAACEdEose0cBA[0-9A-Za-z]+	0	gf_facebook_access_token	High	Certain
basic\s*[a-zA-Z0-9=:_\+\/-]+	0	gf_authorization_basic	High	Certain
bearer\s*[a-zA-Z0-9_\-\.=:_\+\/]+	0	gf_authorization_bearer	High	Certain
api[key|\s*]+[a-zA-Z0-9_\-]+	0	gf_authorization_api	High	Certain
key-[0-9a-zA-Z]{32}	0	gf_mailgun_api_key	High	Certain
SK[0-9a-fA-F]{32}	0	gf_authorization_api	High	Certain
AC[a-zA-Z0-9_\-]{32}	0	gf_twilio_api_key	High	Certain
AP[a-zA-Z0-9_\-]{32}	0	gf_twilio_account_sid	High	Certain
access_token\$production\$[0-9a-z]{16}\$[0-9a-f]{32}	0	gf_paypal_braintree_access_token	High	Certain
sq0csp-[ 0-9A-Za-z\-_]{43}|sq0[a-z]{3}-[0-9A-Za-z\-_]{22,43}	0	gf_square_oauth_secret	High	Certain
sqOatp-[0-9A-Za-z\-_]{22}|EAAA[a-zA-Z0-9]{60}	0	gf_square_access_token	High	Certain
rk_live_[0-9a-zA-Z]{24}	0	gf_stripe_restricted_api	High	Certain
[a-zA-Z0-9_-]*:[a-zA-Z0-9_\-]+@github\.com*	0	gf_github_access_token	High	Certain
-----BEGIN RSA PRIVATE KEY-----	0	gf_rsa_private_key	High	Certain
-----BEGIN DSA PRIVATE KEY-----	0	gf_ssh_dsa_private_key	High	Certain
-----BEGIN EC PRIVATE KEY-----	0	gf_ssh_dc_private_key	High	Certain
-----BEGIN PGP PRIVATE KEY BLOCK-----	0	gf_pgp_private_block	High	Certain
ey[A-Za-z0-9_-]*\.[A-Za-z0-9._-]*|ey[A-Za-z0-9_\/+-]*\.[A-Za-z0-9._\/+-]*	0	gf_json_web_token	High	Certain
(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])	0	gf_ip	High	Certain
CURLOPT_(HTTPHEADER|HEADER|COOKIE|RANGE|REFERER|USERAGENT|PROXYHEADER)	0	gf_php_curl	High	Certain
aws_access|aws_secret|api[_-]?key|ListBucketResult|S3_ACCESS_KEY|Authorization:|RSA PRIVATE|Index of|aws_|secret|"ssh-rsa AA"	0	gf_sec	High	Certain
Application-Trace|Routing Error|DEBUG\"? ?[=:] ?True|Caused by:|stack trace:|Microsoft .NET Framework|Traceback|[0-9]:in `|#!/us|WebApplicationException|java\\.lang\\.|phpinfo|swaggerUi|on line [0-9]|SQLSTATE	0	gf_debug_pages	High	Certain
[^a-z0-9_](system|exec|popen|pcntl_exec|eval|create_function|unserialize|file_exists|md5_file|filemtime|filesize|"assert) ?\\("	0	gf_php_sinks	High	Certain
[A-Za-z\.]+\({1}+([A-Za-z0-9]+\s+[A-Za-z0-9]+(, )?)*\){1}+\s\+{1}+\d++	0	ASP.Net	Low	Certain	3
"Message":"Invalid web service call	0	ASP.Net	Low	Certain
Exception of type	0	ASP.Net	Low	Certain
--- End of inner exception stack trace ---	0	ASP.Net	Low	Certain
Microsoft OLE DB Provider	0	ASP.Net	Low	Certain
Error ([\d-]+) \([\dA-Fa-f]+\)	0	ASP.Net	Low	Certain
\bat ([a-zA-Z0-9_]*\.)*([a-zA-Z0-9_]+)\([a-zA-Z0-9, \[\]\&\;]*\)	0	ASP.Net	Low	Certain 3
([A-Za-z]+[.])+[A-Za-z]*Exception: 	0	ASP.Net	Low	Certain 2
in [A-Za-z]:\\([A-Za-z0-9_]+\\)+[A-Za-z0-9_\-]+(\.aspx)?\.cs:line [\d]+	0	ASP.Net	Low	Certain	2
Syntax error in string in query expression	0	ASP.Net	Medium	Certain
\.java:[0-9]+	0	Java	Low	Certain
\.java\((Inlined )?Compiled Code\)	0	Java	Low	Certain	2
\.invoke\(Unknown Source\)	0	Java	Low	Certain
nested exception is	0	Java	Low	Firm
\.js:[0-9]+:[0-9]+	0	Javascript	Low	Certain
JBWEB[0-9]{6}:	0	JBoss	Low	Firm
((dn|dc|cn|ou|uid|o|c)=[\w\d]*,\s?){2,}	0	LDAP	Low	Firm
\[(ODBC SQL Server Driver|SQL Server|ODBC Driver Manager)\]	0	Microsoft SQL Server	Low	Certain
Cannot initialize the data source object of OLE DB provider "[\w]*" for linked server "[\w]*"	0	Microsoft SQL Server	Low	Certain
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near	0	MySQL	Medium	Certain
Illegal mix of collations \([\w\s\,]+\) and \([\w\s\,]+\) for operation	0	MySQL	Medium	Certain
at (\/[A-Za-z0-9\.]+)*\.pm line [0-9]+	0	Perl	Low	Certain
\.php on line [0-9]+	0	PHP	Low	Certain
\.php</b> on line <b>[0-9]+	0	PHP	Low	Certain
Fatal error:	0	PHP	Low	Certain
\.php:[0-9]+	0	PHP	Low	Certain
Traceback \(most recent call last\):	0	Python	Low	Certain
File \"[A-Za-z0-9\-_\./]*\", line [0-9]+, in	0	Python	Low	Certain
\.rb:[0-9]+:in	0	Ruby	Low	Certain
\.scala:[0-9]+	0	Scala	Low	Certain
\(generated by waitress\)	0	Waitress Python server	Information	Certain
132120c8|38ad52fa|38cf013d|38cf0259|38cf025a|38cf025b|38cf025c|38cf025d|38cf025e|38cf025f|38cf0421|38cf0424|38cf0425|38cf0427|38cf0428|38cf0432|38cf0434|38cf0437|38cf0439|38cf0442|38cf07aa|38cf08cc|38cf04d7|38cf04c6|websealerror	0	WebSEAL	Low	Certain	2
